org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

version=26.1.x-1.5.0
group=ga.ozli.minecraftmods.variablespawnerhardness

minecraft_version=26.1.2
forge_version=64.0.5
fabric_loader_version=0.18.4
neo_version=26.1.2.27-beta
