org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.configureondemand=true

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=25w32a
	loader_version=0.17.2

# Mod Properties
	mod_version = 1.21.9-25w32a-1.4.3
	maven_group = ga.ozli.minecraftmods.variablespawnerhardness
	archives_base_name = VariableSpawnerHardness

# Dependencies
	mc_dep_version = 1.21.9-alpha.25.32.a
	java_version = 21
