plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
}

minecraft {
    runs {
        configureEach {
            workingDir = this.layout.projectDirectory.dir('../run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }

        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

// Implement mcgradleconventions loader attribute
final loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
